production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: admin
  password: password123
  database: ukokkei1_production
development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: admin
  password: password123
  database: ukokkei1_development
test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: admin
  password: password123
  database: ukokkei1_test
